import json
import logging
import re
from groq import AsyncGroq
from core.config import settings
from models.schemas import AgentAction, CanvasShape
from typing import List, Optional
from services.canvas_service import find_empty_position

# Setup logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Initialize Groq client
client = AsyncGroq(api_key=settings.GROQ_API_KEY)

async def get_agent_actions(user_message: str, shapes: List[CanvasShape], agent_mode: str) -> List[AgentAction]:
    """
    Calls the Groq API to get agent actions. 
    Overrides coordinates using canvas_service for spatial intelligence.
    """
    from services.canvas_service import build_canvas_context
    canvas_context = build_canvas_context(shapes)

    prompt = f"""
Canvas state:
{canvas_context}

User says:
{user_message}

Agent mode: {agent_mode}

Goal: Provide high-quality brainstorm ideas. 
Do NOT worry about exact x, y coordinates. Focus on idea quality.
The backend will place items correctly in a grid.

"tentative" mode (VERY IMPORTANT):
Unless the user explicitly asks for a DIRECT change (like "delete shape X" or "group these two"), you MUST suggest ideas as tentative.
- If proposing new content, set "tentative": true.
- Explain WHY you are suggesting this in the "reasoning" field (20-30 words).
- If the user asks for a brainstorm, ALL your ideas should be tentative.
- Keep ideas professional but creative.

Return ONLY a JSON array of actions:
[
  {{
    "action": "place_sticky",
    "content": "Idea Title",
    "reasoning": "This fits here because...",
    "tentative": true
  }}
]

Note: "action" must be one of: "place_sticky", "update_shape", "delete_shape".
If returning multiple ideas, use the array format.
"""

    try:
        if not settings.GROQ_API_KEY:
            logger.warning("GROQ_API_KEY is not set. Falling back to default action.")
            return [_get_fallback_action(shapes)]

        chat_completion = await client.chat.completions.create(
            messages=[
                {
                    "role": "system",
                    "content": "You are an AI assistant for a brainstorm canvas. You help users organize ideas. Always respond with valid JSON."
                },
                {
                    "role": "user",
                    "content": prompt,
                }
            ],
            model="llama-3.3-70b-versatile",
        )

        response_text = chat_completion.choices[0].message.content.strip()
        logger.info(f"Raw Model Output: {response_text}")

        # Clean response if model wrapped it in markdown
        json_match = re.search(r"\[\s*{.*}\s*\]", response_text, re.DOTALL)
        if not json_match:
            # Try single object if array not found
            json_match = re.search(r"{\s*.*\s*}", response_text, re.DOTALL)

        if json_match:
            response_text = json_match.group(0)
        
        try:
            action_data = json.loads(response_text)
            if isinstance(action_data, dict):
                action_data = [action_data]
            
            actions = []
            for index, data in enumerate(action_data):
                # Override position
                nx, ny = find_empty_position(shapes, keywords=data.get("content"))
                data["x"] = nx
                data["y"] = ny
                # Ensure all required fields for AgentAction
                if "reasoning" not in data: data["reasoning"] = "Generated by AI"
                if "shape_id" not in data or not data["shape_id"]: 
                    data["shape_id"] = f"idea-{index}-{int(asyncio.get_event_loop().time())}"
                actions.append(AgentAction(**data))
            return actions

        except (json.JSONDecodeError, ValueError) as e:
            logger.error(f"JSON Parse Error: {e}. Attempting text-to-action fallback.")
            # Fallback: Treat as plain text and split by bullets/newlines
            lines = [line.strip("- *•").strip() for line in response_text.split("\n") if line.strip()]
            actions = []
            for line in lines:
                if len(line) > 5: # Ignore very short artifacts
                    nx, ny = find_empty_position(shapes, keywords=line)
                    actions.append(AgentAction(
                        action="place_sticky",
                        content=line,
                        x=nx,
                        y=ny,
                        reasoning="Extracted from unstructured AI output.",
                        tentative=False
                    ))
            return actions if actions else [_get_fallback_action(shapes)]

    except Exception as e:
        logger.error(f"Error calling Groq API: {e}")
        return [_get_fallback_action(shapes)]

def _get_fallback_action(shapes: List[CanvasShape]) -> AgentAction:
    nx, ny = find_empty_position(shapes)
    return AgentAction(
        action="place_sticky",
        content="I'm thinking... let's try another approach.",
        x=nx,
        y=ny,
        reasoning="System fallback due to error.",
        tentative=False
    )
